### ISSUE TITLE
dependency missing - xclip on ubuntu

### ISSUE THREAD

**Issue by chrisbward** [marionebl/share-cli#1]
http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js/27688805#27688805

spawn called
{ '0': 'xclip', '1': [ '-selection', 'clipboard' ] }
/home/developer/.nvm/versions/node/v4.3.2/lib/node_modules/share-cli/cli.js:328
			throw error;
			^

Error: spawn xclip ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

I solved this by sudo apt-get install xclip, you may want to update the docs

**Comment by marionebl** [comment]
Thanks for reporting this! The relevant upstream bug for this is: https://github.com/xavi-/node-copy-paste/issues/57

**Comment by marionebl** [comment]
That being said i think we should catch this and print a warning instead of throwing that tells you about the neat hidden feature you are missing out on.

**Comment by marionebl** [comment]
Fixed with v2.0.0
