### ISSUE TITLE
This module uses 117% CPU

### ISSUE THREAD

**Issue by dolanmiu** [marionebl/share-cli#5]
![image](https://user-images.githubusercontent.com/2917613/45316461-0cf0d400-b52f-11e8-9cd4-064cc7320b5c.png)

Not sure why it does this, but its incredibly slow for me

To reproduce:
1. Go to repo readme where image is at
2. Launch chrome task manager

**Comment by marionebl** [comment]
Thanks for reporting. This most likely is an issue with the SVG rendered via [svg-term-cli](https://github.com/marionebl/svg-term-cli). If the problem persists you might want to consider creating an issue there.
