### ISSUE TITLE
[Question] How to be possible share a browser?

### ISSUE THREAD

**Issue by Kikobeats** [marionebl/share-cli#7]
Hello,

I love how minimal and focused is this project. Thanks for that!

In order to extend the idea, I want to the same but for [`bcat`](https://github.com/kessler/node-bcat#node-bcat).

`bcat` is just a simple tool to pipe any UNIX command to them and print the output in a browser instead of the terminal

![](https://camo.githubusercontent.com/5796043cac6e25f6c63485a43b44d60ceb1fa837/68747470733a2f2f7261772e6769746875622e636f6d2f6b6573736c65722f7374617469632f6d61737465722f6e6f64652d626361742e706e67)

The point is, this tab runs on my local – Could be possible convert the that into a shareable thing? then anyone with the link can see the output, it would be very useful for debugging things.

How I can replicate share functionality to use the same logic but for a different purpose?

🙂

**Comment by marionebl** [comment]
Thanks for reaching out - `bcat` is really interesting. What enables the remote sharing in `share-cli` is the [localtunnel](https://github.com/localtunnel/localtunnel) package and service. 

Without writing any code you can achieve this:

```sh
npx -p localtunnel lt --port 8081 

# Another terminal
echo "setInterval(() => console.log('Hello'), 1000)" > hello.js
node hello.js | npx bcat --port 8081
```

You could also send a PR to bcat to use the localtunnel package directly.

**Comment by Kikobeats** [comment]
thanks for the advice!

Although using `localtunnel` with a simple http server on my local works like a charm, when I do the same but using `bcat` the tunnel is not showing any output 🤔

**Comment by Kikobeats** [comment]
strongly related: https://github.com/mthenw/frontail
